export default [
  {
    id: 0,
    number: 0,
    TotalStaked: 672,
    TotalOwned: 183,
    AvailableSlots: 7,
    Link: "DzWPTj1Ym5w5uGoGvdjtRK6GyoG4VpjL8VJhdUcSRfqg",
  },
  {
    id: 1,
    number: 1,
    TotalStaked: 140,
    TotalOwned: 0,
    AvailableSlots: 2,
    Link: "DzWPTj1Ym5w5uGoGvdjtRK6GyoG4VpjL8VJhdUcSRfqg",
  },
  {
    id: 2,
    number: 2,
    TotalStaked: 1917,
    TotalOwned: 0,
    AvailableSlots: 2,
    Link: "5Hz47x9T5EpVC6SPK3iwFnAtQvmLuKBf7tMa4z1CTVmS",
  },
  {
    id: 3,
    number: 3,
    TotalStaked: 609,
    TotalOwned: 137,
    AvailableSlots: 3,
    Link: "DzWPTj1Ym5w5uGoGvdjtRK6GyoG4VpjL8VJhdUcSRfqg",
  },
  {
    id: 4,
    number: 4,
    TotalStaked: 672,
    TotalOwned: 56,
    AvailableSlots: 8,
    Link: "DzWPTj1Ym5w5uGoGvdjtRK6GyoG4VpjL8VJhdUcSRfqg",
  },
  {
    id: 5,
    number: 5,
    TotalStaked: 178,
    TotalOwned: 99,
    AvailableSlots: 2,
    Link: "GAMzvYjvJitCzrFyLk58uomE6dBEhSzzVfBJvdphTGQs",
  },
  {
    id: 6,
    number: 6,
    TotalStaked: 1922,
    TotalOwned: 4,
    AvailableSlots: 4,
    Link: "DzWPTj1Ym5w5uGoGvdjtRK6GyoG4VpjL8VJhdUcSRfqg",
  },
  {
    id: 7,
    number: 7,
    TotalStaked: 1077,
    TotalOwned: 4,
    AvailableSlots: 2,
    Link: "DrLky4KzLnKUtdcVoYGyKkiSmhWkBt4npANphHf6SEV9",
  },
];
